### ISSUE TITLE
Missing fonts 

### ISSUE THREAD

**Issue by alculete** [batosti/whatsapp-desktop#1]
![image](https://github.com/batosti/whatsapp-desktop/assets/2129497/66e5d728-0b08-48e3-8779-2f1850235ab9)

**Comment by batosti** [comment]
This are happening in which language? Can you provide the steps to I try to reproduce this error?

**Comment by alculete** [comment]
I have downloaded a document and tried to save the document

**Comment by batosti** [comment]
witch language are your device?

**Comment by alculete** [comment]
Sorry English

**Comment by batosti** [comment]
We don't have the steps enough to reproduce the issue.
